package it.polimi.mw.compinf.logging.spark;

public enum SparkQueries {
	COMPLETED_PER_MINUTE,
	COMPLETED_PER_HOUR,
	COMPLETED_PER_DAY,
	COMPLETED_PER_WEEK,
	COMPLETED_PER_MONTH,
	AVERAGE_STARTING,
	PENDING_TASKS
}
