#!/bin/bash

usage() {
  echo "Usage: akka node start [role] [port] [seed node] [kafka server]" ; exit 1
}

startNode() {
  role=$1
  port=$2
  seed=$3
  kafka=$4

  scriptPath=$(dirname $0)
  scriptPathFull=$(cd $(dirname $0) ; pwd -P)
  jarFilename="$scriptPath/target/compute-infrastructure-akka-node.jar"
  logFilename="$scriptPath/log/$role-$(date +%s).log"

  echo "Starting $role node on port $port"
  java -jar $jarFilename $role $port $seed $kafka &> $logFilename &
}

[ $# -eq 0 ] && usage

if [ $# -eq 4 ] ; then
  startNode "$@"
else
  echo "Invalid parameters."
  usage
fi



