#!/bin/bash

usage() {
  echo "Usage: akka node start [port] [role] [seed node] [kafka server]" ; exit 1
}

startNode() {
  port=$1
  role=$2
  seed=$3
  kafka=$4

  localIp=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')
  export local_ip=$localIp

  scriptPath=$(dirname $0)
  scriptPathFull=$(cd $(dirname $0) ; pwd -P)
  jarFilename="$scriptPath/target/compute-infrastructure-akka-node.jar"
  logFilename="$scriptPath/log/$role-$(date +%s).log"

  echo "Starting $role node on port $port"
  java -jar $jarFilename $port $role $seed $kafka &> $logFilename &
}

[ $# -eq 0 ] && usage

if [ $# -eq 4 ] ; then
  startNode "$@"
else
  echo "Invalid parameters."
  usage
fi



