#!/bin/bash

usage() {
  echo "Usage: akka node stop [port]" ; exit 1
}

stopNode() {
  port=$1

  node="compute-infrastructure-akka-node.jar $port"

  echo "Stopping node on port $port"
  pkill -f "$node"
}

[ $# -eq 0 ] && usage

if [ $# -eq 1 ] ; then
  stopNode $1
else
  echo "Invalid parameters."
  usage
fi