#!/bin/bash

usage() {
  echo "Usage: akka node start [role] [port] [seed node] [kafka server]" ; exit 1
}

startNode() {
  role=$1
  port=$2
  seed=$3
  kafka=$4

  path=$(pwd -P)
  jarFilename="compute-infrastructure-akka-node.jar"

  echo "Starting $role on port $port"
  java -jar $path/target/$jarFilename $role $port $seed $kafka
}

echo $#

[ $# -eq 0 ] && usage

if [ $# -eq 10 ] ; then
  startNode $node
else
  echo "Invalid parameters."
  usage
fi



